"""
NyayaBench scorer — golden-response regression suite.

Locks the scorer against the historical bug family (all "Latin/English-only"
scoring branches that silently penalised correct Indic answers):

  #1  CONFIDENCE_PATTERN missing NONE                  -> confidence undetected
  #2  philosopher regex Latin-only                     -> Indic citations scored 0
  #3  D2 substance gate                                -> terse-valid vs empty
  #4  SIDDHANTA_BACKREF (D5) Latin-only                -> Indic refutations scored 0
  #5  CONFIDENCE_PATTERN natural hedging English-only  -> Indic hedging undetected
  + sweep: D2 Tamil PP marker, TECHNICAL_VOCAB, GENERIC_PHRASES (all were Latin-only)

Expected scores in golden_cases.json are HUMAN-VERIFIED ground truth, hand-traced
from the rubric and signed off — they are NOT generated by the scorer.

Run:  python -m pytest nyaya_bench/tests/test_scorer_golden.py -v
"""

import json
import sys
from pathlib import Path

import pytest

# evaluator.py lives one directory up (nyaya_bench/).
_NYAYA_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_NYAYA_DIR))

import evaluator as ev  # noqa: E402

GOLDEN_PATH = _NYAYA_DIR / "golden_cases.json"
DIMS = [
    ("D1", "format_adherence"),
    ("D2", "purvapaksha_quality"),
    ("D3", "confidence_calibration"),
    ("D4", "language_consistency"),
    ("D5", "siddhanta_quality"),
]


def _load_cases():
    with open(GOLDEN_PATH, encoding="utf-8") as f:
        return json.load(f)["cases"]


CASES = _load_cases()
BY_ID = {c["id"]: c for c in CASES}


def _question(case):
    return {
        "id": case["id"],
        "question": case["question"],
        "language": case["language"],
        "domain": case["domain"],
        "difficulty": case["difficulty"],
        "expected_purvapaksha_sources": case.get("expected_purvapaksha_sources", []),
    }


def _score(case):
    return ev.score_response(_question(case), case["model_answer"])


# ---------------------------------------------------------------------------
# Full golden-set lock — every dimension of every case, exact match.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("case", CASES, ids=[c["id"] for c in CASES])
def test_golden_case_scores_exactly(case):
    result = _score(case)
    s = result["scores"]
    exp = case["expected"]
    for short, col in DIMS:
        assert s[col] == exp[short], (
            f"{case['id']} {short} expected {exp[short]} got {s[col]} "
            f"({case['key_assertion']})"
        )
    assert s["total"] == exp["total"], f"{case['id']} total"
    assert result["passed"] == exp["pass"], f"{case['id']} pass flag"


# ---------------------------------------------------------------------------
# Bug #1 — confidence NONE must register as NONE, not as missing/zero.
# Revert guard: drop NONE from CONFIDENCE_PATTERN -> these go red.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cid", ["GA-01", "GA-02", "GA-03", "GA-04"])
def test_bug1_confidence_none_detected(cid):
    case = BY_ID[cid]
    det = _score(case)["details"]["confidence_calibration"]
    assert det["signal_present"] is True, f"{cid}: NONE not detected as a signal"
    assert det["level_detected"] == "NONE", f"{cid}: level must be NONE, got {det['level_detected']}"
    assert _score(case)["scores"]["confidence_calibration"] == 2, f"{cid}: NONE must not score 0"


# ---------------------------------------------------------------------------
# Bug #2 — a correct non-Latin philosopher citation is credited IDENTICALLY
# to its Latin form, in both the purvapaksha (D2) and the siddhanta (D5).
# Revert guard: strip Indic names from NAMED_PHILOSOPHERS -> twins diverge.
# ---------------------------------------------------------------------------

def test_bug2_philosopher_citation_parity():
    twins = ["GB-01", "GB-02", "GB-03", "GB-04"]
    d2 = {cid: _score(BY_ID[cid])["scores"]["purvapaksha_quality"] for cid in twins}
    d5 = {cid: _score(BY_ID[cid])["scores"]["siddhanta_quality"] for cid in twins}
    assert set(d2.values()) == {3}, f"D2 parity broken across scripts: {d2}"
    assert set(d5.values()) == {2}, f"D5 parity broken across scripts: {d5}"


@pytest.mark.parametrize("cid", ["GB-02", "GB-03", "GB-04"])
def test_bug2_indic_citation_not_zero(cid):
    # The specific historical failure: a correct Tamil/Devanagari/Gurmukhi
    # citation scoring 0 on the citation dimension.
    assert _score(BY_ID[cid])["scores"]["purvapaksha_quality"] == 3


# ---------------------------------------------------------------------------
# Bug #3 — D2 substance gate: terse-but-substantive Indic passes (3),
# genuinely empty/evasive fails (0). Concision must not be punished.
# Revert guard: remove Indic verbs from OBJECTION_VERB -> terse cases drop to 2.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cid", ["GC-01", "GC-02"])
def test_bug3_terse_indic_passes_gate(cid):
    case = BY_ID[cid]
    det = _score(case)["details"]["purvapaksha_quality"]
    assert det["substance_verb_found"] is True, f"{cid}: Indic objection verb not detected"
    assert det["pp_word_count"] < ev.D2_SUBSTANCE_MIN_WORDS, f"{cid}: not actually terse"
    assert _score(case)["scores"]["purvapaksha_quality"] == 3, f"{cid}: terse-valid must score 3"


def test_bug3_empty_fails_gate():
    assert _score(BY_ID["GC-03"])["scores"]["purvapaksha_quality"] == 0


# ---------------------------------------------------------------------------
# Bug #4 — D5 SIDDHANTA_BACKREF must recognise Indic rebuttal connectives.
# Revert guard: revert SIDDHANTA_BACKREF to Latin-only -> Indic D5 -> 0.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("cid", ["GA-02", "GA-03", "GA-04", "GB-02", "GB-03", "GB-04"])
def test_bug4_indic_siddhanta_backref_credited(cid):
    case = BY_ID[cid]
    det = _score(case)["details"]["siddhanta_quality"]
    assert det["backref_found"] is True, f"{cid}: Indic backref not detected (D5 Latin-only regression?)"
    assert _score(case)["scores"]["siddhanta_quality"] >= 1, f"{cid}: Indic siddhanta scored 0"


# ---------------------------------------------------------------------------
# Bug #5 — confidence calibration must detect native-script natural-language
# hedging (partial credit), not only English / the [CONFIDENCE:] bracket.
# Revert guard: revert CONFIDENCE_PATTERN natural-language half to English-only.
# ---------------------------------------------------------------------------

def test_bug5_golden_native_hedge_partial_credit():
    case = BY_ID["GA-07"]
    det = _score(case)["details"]["confidence_calibration"]
    assert det["signal_present"] is True, "Tamil natural hedge not detected as a signal"
    assert det["level_detected"] is None, "GA-07 has no explicit level token"
    assert _score(case)["scores"]["confidence_calibration"] == 1, "native hedge must earn partial credit (1)"


@pytest.mark.parametrize("lang,text", [
    ("tamil",   "இதை உறுதியாகச் சொல்ல முடியாது; ஒருவேளை தவறாக இருக்கலாம்."),
    ("hindi",   "मैं इसे निश्चित रूप से नहीं कह सकता; शायद यह गलत हो।"),
    ("punjabi", "ਮੈਂ ਇਸਨੂੰ ਪੱਕਾ ਨਹੀਂ ਕਹਿ ਸਕਦਾ; ਸ਼ਾਇਦ ਇਹ ਗਲਤ ਹੋਵੇ।"),
])
def test_bug5_native_hedging_detected_each_script(lang, text):
    score, det = ev.score_confidence_calibration(text, domain="free_will", difficulty="standard")
    assert det["signal_present"] is True, f"{lang}: native hedging undetected (English-only regression?)"
    assert score >= 1, f"{lang}: native hedging scored 0"


# ---------------------------------------------------------------------------
# Sweep guards — the remaining Latin-only branches found in the systemic pass.
# ---------------------------------------------------------------------------

def test_sweep_tamil_pp_marker_only_ettirvaadham():
    # PP heading uses ONLY the canonical Tamil step word எதிர்வாதம் (no பூர்வபக்ஷம்).
    # The D2 extractor must still isolate the PP section so the named source counts.
    ans = (
        "முன்மொழிவு: அனுமானம் செல்லுபடியானது.\n"
        "எதிர்வாதம்: நாகார்ஜுன வாதிடுகிறார் அபோஹம் மட்டுமே என்று.\n"
        "சித்தாந்தம்: ஆயினும் இந்த எதிர்வாதம் தவறானது."
    )
    score, det = ev.score_purvapaksha_quality(ans, expected_sources=["Nagarjuna"])
    assert det["broad_philosopher_found"] is True
    assert score == 3, "Tamil எதிர்வாதம் PP marker not honoured by D2 extractor"


def test_sweep_technical_vocab_indic():
    # Native-script technical term (अनुमान) + Indic backref -> D5 == 2.
    sid = "सिद्धांत: तथापि यह आपत्ति गलत है क्योंकि अनुमान वास्तविक है।"
    score, det = ev.score_siddhanta_quality(sid)
    assert det["technical_vocab_found"] is True, "Indic technical vocab undetected"
    assert score == 2


def test_sweep_generic_phrases_indic():
    # Indic vague, un-attributed objection (no name/school) must reach the D2=1 floor.
    ans = (
        "पूर्वपक्ष: कुछ लोग कहते हैं कि यह गलत है।\n"
        "सिद्धांत: तथापि यह ठीक है।"
    )
    score, det = ev.score_purvapaksha_quality(ans, expected_sources=[])
    assert det["broad_philosopher_found"] is False
    assert det["named_school_found"] is False
    assert score == 1, "Indic generic objection not credited the D2=1 floor"
